version: '3.4'

secrets: 
  config_json:
    file: secrets.json

services:
  cloudflare-ddns:
      image: oznu/cloudflare-ddns:latest
      restart: always
      environment:
        - API_KEY=${API_KEY}
        - ZONE=fssarasp.top
        - PROXIED=true
  frontend: 
    container_name: miralis-front
    image: miralis-front-img
    hostname: wiki.fssarasp.top
    build: 
      context: app/web
      dockerfile: ./Dockerfile
    ports:
      - 25173:25173
    depends_on:
      - backend
  backend:
    container_name: miralis_back
    image: miralis-back-img
    build: 
      context: app/backend
      dockerfile: ./Dockerfile
    ports: 
      - 8443:8443
    volumes:
      - ~/Miralis_data/pb_data:/pb/pb_data

networks:
  default:
    external: true
    name: rasp