version: '3.4'

services:
  frontend: 
    container_name: miralis-front
    image: miralis-front-img
    build: 
      context: app/web
      dockerfile: ./Dockerfile
    ports:
      - 25173:80
    depends_on:
      - backend
  backend:
    container_name: miralis_back
    image: miralis-back-img
    build: 
      context: app/backend
      dockerfile: ./Dockerfile
    ports: 
      - 8186:8186
    volumes:
      - ~/Miralis_data/pb_data:/pb/pb_data